import { StockItem, PreOrderItem, SaleItem, StorageCapacity, iPhoneCondition } from '../types';

export const IPHONE_MODELS = [
  'iPhone 16 Pro Max',
  'iPhone 16 Pro',
  'iPhone 16 Plus',
  'iPhone 16',
  'iPhone 15 Pro Max',
  'iPhone 15 Pro',
  'iPhone 15 Plus',
  'iPhone 15',
  'iPhone 14 Pro Max',
  'iPhone 14 Pro',
  'iPhone 14 Plus',
  'iPhone 14',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro',
  'iPhone 13',
  'iPhone 13 mini',
  'iPhone 12 Pro Max',
  'iPhone 12 Pro',
  'iPhone 12',
  'iPhone 11 Pro Max',
  'iPhone 11 Pro',
  'iPhone 11',
];

export const STORAGE_OPTIONS: StorageCapacity[] = ['64GB', '128GB', '256GB', '512GB', '1TB'];

export const CONDITION_OPTIONS: iPhoneCondition[] = [
  'Novo / Lacrado',
  'Seminovo Grade A+',
  'Seminovo Grade A',
  'Seminovo Grade B',
  'Seminovo Grade C',
];

export const COLOR_OPTIONS = [
  'Titânio Natural',
  'Titânio Preto',
  'Titânio Branco',
  'Titânio Deserto',
  'Titânio Azul',
  'Preto Espacial',
  'Prata',
  'Dourado',
  'Grafite',
  'Meia-noite',
  'Estelar',
  'Azul',
  'Rosa',
  'Verde',
  'Roxo',
  'Vermelho (PRODUCT)RED',
];

export const INITIAL_STOCK: StockItem[] = [
  {
    id: 'stock-1',
    model: 'iPhone 16 Pro Max',
    storage: '256GB',
    color: 'Titânio Deserto',
    batteryHealth: 100,
    condition: 'Novo / Lacrado',
    imei: '359482109847123',
    costPrice: 7200,
    salePrice: 8690,
    supplier: 'Distribuidora Miami Prime',
    status: 'disponivel',
    notes: 'Lacrado com 1 ano de garantia Apple oficial',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'stock-2',
    model: 'iPhone 15 Pro',
    storage: '128GB',
    color: 'Titânio Natural',
    batteryHealth: 96,
    condition: 'Seminovo Grade A+',
    imei: '352940192847291',
    costPrice: 4600,
    salePrice: 5590,
    supplier: 'Fornecedor SP Tech',
    status: 'disponivel',
    notes: 'Impecável, sem marcas, cabo original incluso',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'stock-3',
    model: 'iPhone 14',
    storage: '128GB',
    color: 'Meia-noite',
    batteryHealth: 89,
    condition: 'Seminovo Grade A',
    imei: '358192039485712',
    costPrice: 2850,
    salePrice: 3490,
    supplier: 'Trade-in Loja',
    status: 'disponivel',
    notes: 'Bateria original em bom estado, tela perfeita',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'stock-4',
    model: 'iPhone 13',
    storage: '128GB',
    color: 'Estelar',
    batteryHealth: 86,
    condition: 'Seminovo Grade B',
    imei: '351829304958201',
    costPrice: 2100,
    salePrice: 2690,
    supplier: 'Fornecedor PR',
    status: 'disponivel',
    notes: 'Pequenas marcas de uso nas laterais, tudo funcional',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'stock-5',
    model: 'iPhone 15',
    storage: '128GB',
    color: 'Rosa',
    batteryHealth: 100,
    condition: 'Novo / Lacrado',
    imei: '357291049281745',
    costPrice: 4200,
    salePrice: 5090,
    supplier: 'Distribuidora Miami Prime',
    status: 'reservado',
    notes: 'Reservado para retirada na sexta-feira',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  }
];

export const INITIAL_ORDERS: PreOrderItem[] = [
  {
    id: 'order-1',
    customerName: 'Lucas Ferreira',
    customerPhone: '(11) 98765-4321',
    model: 'iPhone 16 Pro',
    storage: '256GB',
    color: 'Titânio Preto',
    condition: 'Novo / Lacrado',
    agreedPrice: 7800,
    depositPaid: 2000,
    remainingAmount: 5800,
    estimatedArrival: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    status: 'a_caminho',
    supplier: 'Importadora EUA Express',
    notes: 'Rastreio: BR192837465US - Cliente quer com película e capa instalados',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'order-2',
    customerName: 'Mariana Souza',
    customerPhone: '(21) 99123-8844',
    model: 'iPhone 15 Pro Max',
    storage: '512GB',
    color: 'Titânio Natural',
    condition: 'Seminovo Grade A+',
    agreedPrice: 6200,
    depositPaid: 1500,
    remainingAmount: 4700,
    estimatedArrival: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
    status: 'pendente',
    supplier: 'Fornecedor SP Tech',
    notes: 'Cliente solicitou saúde de bateria acima de 90%',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  }
];

export const INITIAL_SALES: SaleItem[] = [
  {
    id: 'sale-1',
    stockItemId: 'stock-old-1',
    customerName: 'Rodrigo Alves',
    customerPhone: '(11) 97123-4567',
    model: 'iPhone 15 Pro Max',
    storage: '256GB',
    color: 'Titânio Azul',
    condition: 'Seminovo Grade A+',
    imei: '359182736450192',
    costPrice: 5300,
    salePrice: 6490,
    profit: 1190,
    paymentMethod: 'pix',
    saleDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: 'Pagamento à vista no Pix com brinde película de privacidade',
  },
  {
    id: 'sale-2',
    stockItemId: 'stock-old-2',
    customerName: 'Camila Ribeiro',
    customerPhone: '(19) 98345-6789',
    model: 'iPhone 13',
    storage: '128GB',
    color: 'Meia-noite',
    condition: 'Seminovo Grade A',
    imei: '356781290384721',
    costPrice: 2200,
    salePrice: 2850,
    profit: 650,
    paymentMethod: 'cartao_credito',
    installments: 10,
    saleDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    notes: 'Parcelado em 10x sem juros na máquina Stone',
  }
];
